version: '3.4'
services:
  web:
    tty: true
    image: odoo_base:12.0
    depends_on:
      - db
      - wdb
    ports:
      - "8069:8069"
      # Этот порт нужен для лонгполлинга
      - "8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ../odoo12/saas-addons:/mnt/addons/saas-addons
    environment:
      - WDB_SOCKET_SERVER=wdb
      - WDB_NO_BROWSER_AUTO_OPEN=True
      - ODOO_QUEUE_JOB_HOST=saas.127.0.0.1.nip.io
    # TODO: unify parameter passing for different cases to avoid making different branches
    # '--db-filter=^%d$$' в этой записи если не экранировать $, то вызовет ошибку
    command: ['-d', 'saas', '--init', 'saas', '--db-filter=^%d$$', '--load=web,queue_job', '--log-handler=odoo.addons.queue_job:DEBUG', '--workers=3']

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  wdb:
    image: kozea/wdb:3.3.0
    ports: ['1984:1984']

volumes:
  odoo-web-data:
  odoo-db-data:
