version: '3.4'
services:
  web:
    tty: true
    image: odoo_base:12.0
    depends_on:
      - db
      - wdb
    ports:
      - "8069:8069"
      - "8072:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
#      - ../odoo12/odoo/addons/stock:/usr/lib/python3/dist-packages/odoo/addons/stock
      - ../odoo12/extra-addons:/mnt/extra-addons
      - ../odoo12/addons-dev:/mnt/addons/misc-addons
    environment:
      - WDB_SOCKET_SERVER=wdb
      - WDB_NO_BROWSER_AUTO_OPEN=True
#    command: ['-d', 'stock_round', '--init', 'web_enterprise,mrp_workorder,stock_round', '--db-filter=.*', '--workers=0']
#    command: ['-d', 'smlnsk', '--init', 'web_enterprise,mrp_workorder,mrp_preparing', '--db-filter=.*', '--workers=0']
  #    command: ['-d', 'smlnsk', '--init', 'web_enterprise,mrp_workorder,mrp_scrap', '--db-filter=.*', '--workers=0']
    command: ['-d', 'smlnsk', '--init', 'web_enterprise,mrp_workorder_qty', '--db-filter=.*', '--workers=0']

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  wdb:
    image: kozea/wdb:3.3.0
    ports: ['1984:1984']

volumes:
  odoo-web-data:
  odoo-db-data:
